name: Create Release on merge event

on:
  pull_request_target:
    types:
      - closed
    paths:
      - '**/Dockerfile'

env:
  REGESTRY: gcr.io


jobs:
  dummy_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Dummy
        run: |
          echo $(ls -la)


