name: Create java image Release on merge event

on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'sift-java-base/Dockerfile'

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    env:
      DOCKERFILE_PATH: "./sift-java-base"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare Release metadata 
        run: |
          set -euxo pipefail
          JAVA_OPENJDK_NAME=$(grep -E "^FROM.*jdk.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' |  awk -F: '{print $1}' | tr / -)
          JAVA_OPENJDK_VEERSION=$(grep -E "^FROM.*jdk.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' | awk -F: '{print $2}')
          OPEN_TELEMETRY_VERSION=$(grep -E "^ARG OPEN_TELEMETRY_VERSION.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' | awk -F= '{print $2}')
          CLOUD_PROFILER_VERSION=$(grep -E "^ARG CLOUD_PROFILER_VERSION.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' | awk -F= '{print $2}')
          NL=$'\n'
          echo "RELEASE_BODY=JAVA_OPENJDK_NAME=$JAVA_OPENJDK_NAME${NL}JAVA_OPENJDK_VEERSION=$JAVA_OPENJDK_VEERSION${NL}OPEN_TELEMETRY_VERSION=$OPEN_TELEMETRY_VERSION${NL}CLOUD_PROFILER_VERSION=$CLOUD_PROFILER_VERSION" >> $GITHUB_ENV
          JAVA_LAST_TAG=$( git tag --sort=-creatordate | grep java | head -1 | cut -d "_" -f1 | cut -d "v" -f2)
          [[ -z $JAVA_LAST_TAG ]] && JAVA_LAST_TAG=1 || JAVA_LAST_TAG=$((JAVA_LAST_TAG + 1))
          JAVA_LAST_TAG="v"$JAVA_LAST_TAG"_java"
          echo "JAVA_LAST_TAG=$JAVA_LAST_TAG" >> $GITHUB_ENV
          echo $RELEASE_BODY
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            const {JAVA_LAST_TAG} = process.env          
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${JAVA_LAST_TAG}`,
                sha: context.sha
            })
      - name: Create Release
        uses: actions/github-script@v6
        with:
          script: |         
            github.rest.repos.createRelease({
                body: process.env.RELEASE_BODY,
                draft: false,
                generate_release_notes: false,
                name: 'Release DOCKER_IMAGE_FOR:java',
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                skipIfReleaseExists: true
                tag_name: process.env.JAVA_LAST_TAG,
              });



