name: Publish custom Docker Image to GCR

on:
  release:
    types: [published]

env:
  REGESTRY: gcr.io
  PROJECT_ID: sift-shared-data
  RELEASE_NAME: ${{ github.event.release.name }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:     
  prepare_dockerfile_java:
    if: contains(github.event.release.name, 'sift-base-java')
    env:
      DOCKERFILE_PATH: "./sift-base-java"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Validate Dockerfile Path
        run: | 
          set -euxo pipefail
          [[ ! -f "$DOCKERFILE_PATH/Dockerfile" ]] && echo "Dockerfile does not exist in $DOCKERFILE_PATH directory" && exit 1       
      - name: Prepare Dockerfile metadata 
        run: |   
          set -euxo pipefail
          JAVA_OPENJDK_NAME=$(grep -E "^FROM.*jdk.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' |  awk -F: '{print $1}' | tr / -)
          JAVA_OPENJDK_VEERSION=$(grep -E "^FROM.*jdk.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' | awk -F: '{print $2}')
          R_TAG=$(echo $RELEASE_TAG | cut -d "_" -f1)
          IMAGE_NAME=$JAVA_OPENJDK_NAME
          IMAGE_VERSION="$JAVA_OPENJDK_VEERSION-$R_TAG"
          mkdir -p ./assets 
          echo "IMAGE_NAME=$IMAGE_NAME" >> ./assets/Dockerfile_meta
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> ./assets/Dockerfile_meta
          mv $DOCKERFILE_PATH/Dockerfile ./assets/Dockerfile
      - uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets 
  prepare_dockerfile_python: 
    if: contains(github.event.release.name, 'sift-base-python')
    env:
      DOCKERFILE_PATH: "./sift-base-python"  
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: |
          [[ ! -f "$DOCKERFILE_PATH" ]] && echo "folder $DOCKERFILE_PATH does not exist" && exit 1
          mkdir -p ./assets 
          echo "test" > ./assets/Dummyfile
          echo "NOT IMPLEMENTED YET"
      - uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets 
  build_and_push:
      needs: [prepare_dockerfile_java, prepare_dockerfile_python]
      if: |
        always() && 
        (needs.prepare_dockerfile_java.result == 'success' || needs.prepare_dockerfile_java.result == 'skipped') && 
        (needs.prepare_dockerfile_python.result == 'success' || needs.prepare_dockerfile_python.result == 'skipped')
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: assets
            path: ./assets
        - name: Check Docker biuld and push target
          run:
            DOCKER_IMAGE_FOR=NOT_SET
            [[ $RELEASE_NAME == *"java"* ]] && DOCKER_IMAGE_FOR=java
            [[ $RELEASE_NAME == *"python"* ]] && DOCKER_IMAGE_FOR=python
            [[ $DOCKER_IMAGE_FOR == "NOT_SET" ]] && echo "DOCKER_IMAGE_FOR=$DOCKER_IMAGE_FOR" && exit 1
            echo "DOCKER_IMAGE_FOR=$DOCKER_IMAGE_FOR" >> $GITHUB_ENV
        - name: Fetch Dockerfile metadata
          run: |
            set -euxo pipefail
            [[ ! -f "./assets/Dockerfile_meta" ]] || [[ ! -f "./assets/Dockerfile" ]] && echo "either ./assets/Dockerfile_meta or ./assets/Dockerfile does not exist" && exit 1
            while IFS= read -r line; do
              [[ "$line" == *"IMAGE_NAME"* ]] && echo "IMAGE_NAME=$(echo $line | cut -d '=' -f2)" >> $GITHUB_ENV && continue
              [[ "$line" == *"IMAGE_VERSION"* ]] && echo "IMAGE_VERSION=$(echo $line | cut -d '=' -f2)" >> $GITHUB_ENV && continue
            done < ./assets/Dockerfile_meta && echo "Dockerfile metadata parsed successfully"  ||  echo "exit code $? /assets/Dockerfile_meta is empty or does not exist"
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'        
        - name: 'Login to GCP'
          uses: 'google-github-actions/auth@v1'
          with:
            service_account: "${{ secrets.GCLOUD_GH_SA }}"
            credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"
        - name: Build Dockerfile
          run: |
            set -euxo pipefail
            cd ./assets 
            echo $IMAGE_NAME
            echo $IMAGE_VERSION
            docker build -t $IMAGE_NAME:$IMAGE_VERSION .
        - name: 'Configure Docker Client'
          run: |
            echo $(whoami)
            gcloud auth configure-docker ${REGESTRY} --quiet
        - name: Push Dockerfile
          run: |
            set -euxo pipefail
            cd ./assets 
            echo $(ls -la)

            docker buildx build --platform linux/amd64 -t "$REGESTRY/$PROJECT_ID/base/$DOCKER_IMAGE_FOR/$IMAGE_NAME:$IMAGE_VERSION" . --push

            echo "docker image $$REGESTRY/$PROJECT_ID/base/$DOCKER_IMAGE_FOR/$IMAGE_NAME:$IMAGE_VERSION has been pushed successfully"