name: JavaImage2Gcr

on:
  release:
    types: [published]
    paths:
      - 'sift-java-base/*'

env:
  REGESTRY: gcr.io
  PROJECT_ID: sift-shared-data
  DOCKERFILE_PATH: "./sift-java-base"  

jobs:
  build_and_publish:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Parse Dockerfile metadata and push
        run: |
          echo "start"
          ls -la
          set -euxo pipefail
          JAVA_OPENJDK_NAME=$(grep -E "^FROM.*jdk.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' | awk -F'/'  '{print $2}' | awk -F: '{print $1}')
          JAVA_OPENJDK_VEERSION=$(grep -E "^FROM.*jdk.*$" $DOCKERFILE_PATH/Dockerfile | awk -F' '  '{print $2}' | awk -F'/'  '{print $2}' | awk -F: '{print $2}')
          VER=$(echo $RELEASE_NAME | awk -F: '{print $1}')

          [ -d "$DOCKERFILE_PATH" ] && cd $DOCKERFILE_PATH  
          IMAGE_NAME="$JAVA_OPENJDK_NAME"
          IMAGE_TAG="$JAVA_OPENJDK_VEERSION-$VER"

          [ -z "$IMAGE_NAME" ] || [ -z "$IMAGE_TAG" ] && echo "Failed on parsing $DOCKERFILE_PATH/Dockerfile , IMAGE NAME or TAG is NOT FOUND" && exit 1
          echo "end"
