name: JavaImage2Gcr

on:
  release:
    types: [published]

env:
  REGESTRY: gcr.io
  PROJECT_ID: sift-shared-data
  PATH: "./sift-java-base"  

jobs:
  build_and_publish:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Parse Dockerfile metadata and push
        run: |
          echo "start"
          ls -la
          echo "end"
